# FOSRestBundle Configuration.
fos_rest:
    param_fetcher_listener:
        enabled:              true
    body_converter:
        enabled:              true
        validate:             true
    service:
        serializer:           ~
    body_listener:
        enabled:              true
    format_listener:
        enabled:              true
        service:              null
        rules:
            - { path: ^/api, priorities: [json], fallback_format: 'json', prefer_extension: true }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }